### PR TITLE
Fix for NPE in superuserpassword

### LINKED ISSUE #128: Nilpointer during createBmcSuperuser
```

{"time":"2024-05-31T12:28:36.725260443Z","level":"INFO","msg":"autoreboot set to","machineID":"48eb9200-be80-11e9-8000-3cecef22fc1a","after":"24h0m0s","spread":"24h0m0s"}                                                                                                                                                    
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                                                                                                                       
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xeae002]                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                              
goroutine 1 [running]:                                                                                                                                                                                                                                                                                                        
github.com/metal-stack/metal-hammer/cmd.(*MetalAPIClient).BootService(...)                                                                                                                                                                                                                                                    
        /work/cmd/metal-client.go:81                                                                                                                                                                                                                                                                                          
github.com/metal-stack/metal-hammer/cmd.(*Hammer).createBmcSuperuser(0xc000531b30)                                                                                                                                                                                                                                            
        /work/cmd/supwd.go:14 +0x42                                                                                                                                                                                                                                                                                           
github.com/metal-stack/metal-hammer/cmd.Run(0xc000582580, 0xc00061a000, {0x134adf0, 0xc0004821a0})                                                                                                                                                                                                                            
        /work/cmd/root.go:76 +0x613                                                                                                                                                                                                                                                                                           
main.main()                                                                                                                                                                                                                                                                                                                   
        /work/main.go:92 +0xbf2  
```

### PR DESCRIPTION
**Pull request by majst01**
closes #128 

unexport all fields in the hammer struct

### CODE REVIEW

File: cmd/root.go [hunk 1]
```diff
@@ -20,20 +20,17 @@ import (
...
+type hammer struct {
 	log              *slog.Logger
-	Hal              hal.InBand
-	MetalAPIClient   *MetalAPIClient
-	EventEmitter     *event.EventEmitter
-	LLDPClient       *network.LLDPClient
-	FilesystemLayout *models.V1FilesystemLayoutResponse
+	spec             *Specification
+	hal              hal.InBand
+	metalAPIClient   *MetalAPIClient
```
Comment (majst01) [inline cmd/root.go:28]: This field was deleted

**Review by Gerrit91 — APPROVED** [review]
